---
title: "Module 4 for QMM"
author: "Tongxiang Lu"
date: "2022-09-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lpSolve)
```

```{r}
# First, translate the verbal problem into linear programming maximization algebraic expression.

## Three plants P1, P2 and P3 has three different sizes small(x), medium(y) and large(z).

## Production facilities, plant P1 has x1, y1 and z1 production; plant P2 has x2, y2 and z2 production, and plant P3 has x3, y3 and z3 production.

## The objective function is: Max Z = 420x1 + 360y1 + 300z1 + 420x2 + 360y2 + 300z2 + 420x3 + 360y3 + 300z3

## Subject to: x1 + y1 + z1 ≤ 750,  x2 + y2 + z2 ≤ 900, x3 + y3 + z3 ≤ 450,  20x1 + 15y1 + 12z1 ≤ 13000, 20x2 + 15y2 + 12z2 ≤ 12000, 20x3 + 15y3 + 12z3 ≤ 5000, x1 + x2 + x3 ≤ 900, y1 + y2 + y3 ≤ 1200, z1 + z2 + z3 ≤ 750
                
## The above constraints in equations are listed as follow:  x1 + y1 + z1 + 0x2 + 0y2 + 0z2 + 0x3 + 0y3 + 0z3 ≤ 750, 0x1 + 0y1 + 0z1 + x2 + y2 + z2 + 0x3 + 0y3 + 0z3 ≤ 900, 0x1 + 0y1 + 0z1 + 0x2 + 0y2 + 0z2 + x3 + y3 + z3 ≤ 450, 20x1 + 15y1 + 12z1 + 0x2 + 0y2 + 0z2 + 0x3 + 0y3 + 0z3 ≤ 13000, 0x1 + 0y1 + 0z1 + 20x2 + 15y2 + 12z2 + 0x3 + 0y3 + 0z3 ≤ 12000, 0x1 + 0y1 + 0z1 + 0x2 + 0y2 + 0z2 + 20x3 + 15y3 + 12z3 ≤ 5000, x1 + 0y1 + 0z1 + x2 + 0y2 + 0z2 + x3 + 0y3 + 0z3 ≤ 900, 0x1 + y1 + 0z1 + 0x2 + y2 + 0z2 + 0x3 + y3 + 0z3 ≤ 1200, 0x1 + 0y1 + z1 + 0x2 + 0y2 + z2 + 0x3 + 0y3 + z3 ≤ 750, 

## The coefficients of the constraints can be written in the matrix form as: [ 1 1 1 0 0 0 0 0 0, 0 0 0 1 1 1 0 0 0, 0 0 0 0 0 0 1 1 1, 20 15 12 0 0 0 0 0 0, 0 0 0 20 15 12 0 0 0, 0 0 0 0 0 0 20 15 12, 1 0 0 1 0 0 1 0 0, 0 1 0 0 1 0 0 1 0, 0 0 1 0 0 1 0 0 1]
```

```{r}
# Second, follow the same steps in R Markdown as last lecture learnt to solve the following problem:  
# objective function is to maximize
f.obj <- c(420,360,300, 
           420,360,300,
           420,360,300)
```

```{r}
#constraints
f.con <- matrix(c(1, 1, 1, 0, 0, 0, 0, 0, 0,
                  0, 0, 0, 1, 1, 1, 0, 0, 0,
                  0, 0, 0, 0, 0, 0, 1, 1, 1,
                  20, 15, 12, 0, 0, 0, 0, 0, 0,
                  0, 0, 0, 20, 15, 12, 0, 0, 0,
                  0, 0, 0, 0, 0, 0, 20, 15, 12,
                  1, 0, 0, 1, 0, 0, 1, 0, 0,
                  0, 1, 0, 0, 1, 0, 0, 1, 0,
                  0, 0, 1, 0, 0, 1, 0, 0, 1),nrow=9, byrow = TRUE)
```

```{r}
#set directions of the inequalities
f.dir <- c("<=",
           "<=",
           "<=",
           "<=",
           "<=",
           "<=",
           "<=",
           "<=",
           "<=",
           "<=")
```

```{r}
#set the right hand side of coefficients
f.rhs <- c(750,
           900,
           450,
           13000,
           12000,
           5000,
           900,
           1200,
           750)
```

```{r}
# find the value of functions
lp("max", f.obj, f.con, f.dir, f.rhs)
```

```{r}
# find the value of the variables
lp("max", f.obj, f.con, f.dir, f.rhs)$solution
```